#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  floorOneButton, sensorTouch)
#pragma config(Sensor, dgtl4,  floorTwoButton, sensorTouch)
#pragma config(Sensor, dgtl5,  floorThreeButton, sensorTouch)
#pragma config(Sensor, dgtl6,  timerButton,    sensorTouch)
#pragma config(Motor,  port1,           shaftMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1){
		if(SensorValue[floorOneButton] == 1){
			if(SensorValue[sonar] != 0){
				startMotor(shaftMotor, 63);
				untilSonarLessThan(sonar, 0.1);
			}
		}
		if(SensorValue[floorTwoButton] == 1){
			if(SensorValue[sonar] != 2.5){
				if(SensorValue[sonar] < 2.5){
						startMotor(shaftMotor, 63);
						untilSonarGreaterThan(sonar, 1.4);
				}	
			}	
		}
	}
}
